### PR TITLE
Proposal for the Spanish keywords

### PR DESCRIPTION
**Pull request by jmoralesv**
Proposal for the Spanish keywords, to make them sound better according to the programming context they are going to be used.

I made some of the keywords use the imperative or command form instead of the infinite form (for example, for "open" I chose "abre" instead of "abrir"), because we are telling the computer to execute or do something in our behalf. Spanish grammar is really complex for foreigners, but you can find some examples here: https://www.enforex.com/language/spanish-commands.html

For others, I revert them to the original English keywords because I'm not sure what the context for them is (for example downcast or downto), I don't know F# very well so I would need more info to make a proper translation.

On the other hand, Spanish is a very "verbose" language because we use more words to express the same idea that English would use less words. I made some choices to make them fit to have 1 word per keyword, but maybe a better translation would be a Spanish phrase, such as "else" that I translated as "sino", but I think a better way would have been "de lo contrario", it's more formal as well 😄

### CODE REVIEW

**Comment by kant2002** [comment]
Thank you Jorge, I really appreciate that you spend time on that as native speaker. I understand that this whole translation story is really tricky. Especially given the fact that I plan to change existing compiler as little as possible, otherwise it would be hard to do something meaningful with small resources.

`downcast` is conversion from base class to child class. that keyword can be seen as shorthand for `cast to class down in the hierarchy`. Where parent classes up in the hierarchy. Cast is funny word for me since it hard for me combine two meaning of it.
- Cast as actors play.
- Cast as when you put fluid metal in form, and let it take form after it cooled. 
So it's process of taking other form.

`downto` is easier. it's literally `down to`
`for i = 0 to 10 do` that normal for loop
`for i = 10 downto 0 do` that loop in reverse direction.

**Comment by jmoralesv** [comment]
> Thank you Jorge, I really appreciate that you spend time on that as native speaker. I understand that this whole translation story is really tricky. Especially given the fact that I plan to change existing compiler as little as possible, otherwise it would be hard to do something meaningful with small resources.

No worries! Translating stuff is fun sometimes, I don't normally do this stuff (at work we use English for everything) so doing this translation stuff is a nice thing, for a change :)

> `downcast` is conversion from base class to child class. that keyword can be seen as shorthand for `cast to class down in the hierarchy`. Where parent classes up in the hierarchy. Cast is funny word for me since it hard for me combine two meaning of it.

Thanks for the explanation!  With that in mind, I will take some to think about a better word (or a phrase maybe, in a camelCase fashion?) for `downcast`.

> `downto` is easier. it's literally `down to` `for i = 0 to 10 do` that normal for loop `for i = 10 downto 0 do` that loop in reverse direction.

This would be easier, I'm thinking of using "reverse" or "in reverse" instead, if that is the only way you use `downto`.

Thanks again Andrii for the explanation! I will let you know here once I have updated the PR.

**Comment by kant2002** [comment]
I believe at this stage I would not want strive for perfection. I better merge PR as is, and left words intact. If you have better ideas, you always can go to that repo and improve translation.

**Comment by kant2002** [comment]
Thanks!

**Comment by jmoralesv** [comment]
Hi @kant2002 
Thanks! I'm sorry for the delay, I've been busy with work and family stuff.

Sure, if I can come up with better translations, I will open a new PR again.

Have a nice day 👍

**Pull request merged**
